# Generated by Django 4.2.3 on 2023-07-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_task_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
